### PR TITLE
Download cheats feature

### PR DESCRIPTION
**Pull request by mathhun**

### CODE REVIEW

**Comment by mathhun** [comment]
@mattn I don't understand. All the suggestions are not present in the final 'cheat.go'. What should I fix? Should I just squash all the commits to one?

**Comment by mattn** [comment]
https://patch-diff.githubusercontent.com/raw/dufferzafar/cheat/pull/4.patch

This is a summarized patch file.

https://gist.github.com/mattn/4bf77ec122e6cb618972

and this is same as this patch. I still can see below in this patch.
```
ioutil.TempDir(os.TempDir(), "cheat")
```
in https://gist.github.com/mattn/4bf77ec122e6cb618972#file-gistfile1-diff-L63

```
os.Exit(exitCode)
```
in https://gist.github.com/mattn/4bf77ec122e6cb618972#file-gistfile1-diff-L196

https://gist.github.com/mattn/4bf77ec122e6cb618972#file-gistfile1-diff-L203
This part still not fixed to filepath.

**Comment by mattn** [comment]
Ah, sorry. I'll check it again. Please wait.

**Comment by mattn** [comment]
LGTM. Thanks.

**Comment by mattn** [comment]
@dufferzafar if you are okay, please merge this.

**Comment by mattn** [comment]
:+1:

**Pull request merged**
