### PR TITLE
Implement download cheats feature

### PR DESCRIPTION
**Pull request by mathhun**

### CODE REVIEW

**Comment by dufferzafar** [comment]
This looks good overall. I can't seem to find the time to test & merge yet, but will surely do that as soon as I can.

On a side note, I was thinking of dropping the `cheat fetch` idea, because I had downloading a ZIP file from chris' repo and then extracting the cheats in mind.

Didn't think of cloning the entire repo (which seems like a better way.) Also what happens if a user runs `cheat fetch` again, I think we should just do a  `git pull` if the repo already exists. Your thoughts?

**Comment by mathhun** [comment]
Cloned repo is stored under a temporary directory and removed afterward every time. I thought users don't want to keep the entire repo just for the cheats.
A downside could be it requires git command installed.

**Comment by dufferzafar** [comment]
I wouldn't worry about the `git` command, we just say that you need to have `git` to fetch cheats. 

But storing the entire repo makes sense, because, once people start editing their sheets or begin adding new ones. It'd make sense for them to send pull requests to Chris' repo so that all of us can have some awesome cheats! 

So I think we could just git clone the repo. And just let it be there. And in the readme, we could mention all about how they can contribute sheets. What do you think?

**Comment by mathhun** [comment]
Makes sense.
Revised to keep the repo. Repo path can be specified via GOPATH (assuming many users are Go developers) or a command line flag. It would also be nice if it can be specified in the config file.

**Comment by dufferzafar** [comment]
@mattn What are your thoughts on this?

**Comment by mattn** [comment]
LGTM except my few comments.

**Comment by mattn** [comment]
probably, there are few comments that is already fixed in master branch. so please rebase master.

**Comment by dufferzafar** [comment]
@mathhun Can you please make the suggested changes?

**Comment by mathhun** [comment]
@dufferzafar @mattn 
Fixed according to comments by @mattn. in a new branch: https://github.com/dufferzafar/cheat/pull/4
(couldn't figure out how to 'rebase master' in this same pull request :cry:)

**Comment by dufferzafar** [comment]
@mathhun It's okay. :)

**Pull request closed without merging**
