### PR TITLE
Support Windows

### PR DESCRIPTION
**Pull request by mattn**

### CODE REVIEW

**Comment by dufferzafar** [comment]
Thanks a lot! This looks quite good. :smiley: 

I'm currently on Ubuntu; will test and merge this on my Windows machine. 

BTW, Is the copy to clipboard thing working alright?

**Comment by mattn** [comment]
https://github.com/atotto/clipboard has code for windows. :)

**Comment by mattn** [comment]
any update on this?

**Comment by mattn** [comment]
I'm thinking `$HomeDir` or `~/` should be kept on .cheetrc since configuration file may be portable.

**Comment by dufferzafar** [comment]
I am sorry this has taken so much time. But I don't have access to a Windows machine now. I am [adding you as a contributor to the repository](http://felixge.de/2013/03/11/the-pull-request-hack.html), if that's fine with you. You are now free to rebase and merge this :)

**Comment by mattn** [comment]
Thank you

**Pull request merged**
